### ISSUE TITLE
Gnome Shell (Material You) Visual Bug

### ISSUE THREAD

**Issue by rshchekotov** [NyarchLinux/NyarchLinux#50]
There appears to be a visual bug with the Custom Gnome Shell (Material You).
![Image](https://github.com/user-attachments/assets/32b65d56-7f4e-4ff8-9e95-01bf08d134e3)

Here's the same with Adwaita enabled:

![Image](https://github.com/user-attachments/assets/dde4bdab-ae30-4db9-8ecf-cfc5df292f53)

It wouldn't be such a big issue, if I could switch to Adwaita and just not care, but I like switching to Dark/Light mode depending on the time of day, and some amount of configuration depends on that switch - i.e. Wallpaper switching, etc. - whenever I switch, Nyarch decides to re-apply Material You, re-introducing the visual bug, which can be seen in the screenshot.

**Comment by FrancescoCaracciolo** [comment]
Update Nyarch from Nyarch updater (Or just update material you). This is solved.
If you want to switch to default theme, just disable Material You

**Comment by rshchekotov** [comment]
I did that, there were some updates, I installed those (step-by-step, by pressing execute on all the update prompts), I then checked for other new updates and found none.

![Image](https://github.com/user-attachments/assets/3c0c9997-ebec-408a-9b3b-0ba50c6cf870)

I rebooted the system and yet, the issue persists.
How could I check whether the update has been applied, or - for that matter, how could I further debug the situation or provide you with information that could help identify the issue?

**Comment by FrancescoCaracciolo** [comment]
Probably some bug in Nyarch Updater.

Update using Nyarch Scripts. Material you is the last in the update tab. Just run the script, log out, log in and regenerate the theme

**Comment by rshchekotov** [comment]
Thanks for the fast reply, I did what you suggested and that unfortunately changed nothing.
I did the same procedure (and this time I did see something what looked like a git clone happening).
Rebooted the system again and the bug still persists.

If it helps at all, I presume this is the file which contains the styles pertaining to the bug:
```
sha512sum $HOME/.local/share/themes/MaterialYou/gnome-shell/gnome-shell.css

6382a6da449534977833105f585bd90c0f4f6efc9bcfa34f4b2320210535aec1fffbec9f5a5e8b284a31812afdc4ae7a774331f3a74d842bd970187e57643b84  $HOME/.local/share/themes/MaterialYou/gnome-shell/gnome-shell.css
```
(redacted the path using `$HOME`).

**Comment by rshchekotov** [comment]
I probably have not regenerated the theme, how would I do that?
I have assumed that this was part of the update.

**Comment by FrancescoCaracciolo** [comment]
Change wallpaper or color scheme

**Comment by rshchekotov** [comment]
I changed the wallpaper and changed it back again - that probably regenerated the theme and fixed it!
Thanks a lot for your help, appreciate it very much!
